Repository yodaos-project/ShadowNode, pull requests merged in 2019-01, with the labels that each got.

#477 build: always run jerry tests on non-PR branch
  tools/travis_script.py
Labels: build

#476 module: avoid error when require an empty module fix/gh-330.
  src/modules/iotjs_module_process.c
  test/run_pass/require1/empty_module.js
  test/run_pass/test_module_require.js
Labels: module

#317 array: implement missing routines
  deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c
  deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.inc.h
  deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-helpers.c
  deps/jerry/jerry-core/ecma/builtin-objects/ecma-builtin-helpers.h
  deps/jerry/jerry-core/lit/lit-magic-strings.inc.h
  deps/jerry/jerry-core/lit/lit-magic-strings.ini
  deps/jerry/tests/jerry/array-prototype-copyWithin.js
  deps/jerry/tests/jerry/array-prototype-fill.js
  deps/jerry/tests/jerry/array-prototype-find.js
  deps/jerry/tests/jerry/array-prototype-findIndex.js
  deps/jerry/tests/jerry/array-prototype-includes.js
  deps/jerry/tools/test262/test-262-auto-generator.js
Labels: jerry

#480 mqtt: change the option `keepalive` in seconds.
  src/js/mqtt.js
  test/run_pass/test_mqtt_client.js
Labels: mqtt

#485 Revert "module: add require.resolve (#445)"
  benchmark/module/require.js
  benchmark/module/require.resolve.js
  docs/api/Module.md
  src/js/module.js
  test/common/fixtures.js
  test/run_pass/test_require_resolve.js
  test/testsets.json
Labels: module
